services:
  - type: web
    name: resumemaker-backend
    env: node
    plan: free
    buildCommand: |
      cd backend
      npm install --no-audit --no-fund
      npm run build
    startCommand: |
      cd backend
      npm start
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: DATABASE_URL
        fromDatabase:
          name: resumemaker-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: CORS_ORIGIN
        value: https://your-frontend-domain

databases:
  - name: resumemaker-db
    plan: free

